A-backhand-lib:
- changed-files:
  - any-glob-to-any-file: backhand/**

A-fuzz:
- changed-files:
  - any-glob-to-any-file: fuzz/**

A-backhand-cli:
- changed-files:
  - any-glob-to-any-file: backhand-cli/**

A-tests:
- changed-files:
  - any-glob-to-any-file: backhand-test/**

A-CI:
- changed-files:
  - any-glob-to-any-file: .github/**

A-unsquashfs:
- changed-files:
  - any-glob-to-any-file: backhand-cli/src/bin/unsquashfs.rs

A-add:
- changed-files:
  - any-glob-to-any-file: backhand-cli/src/bin/add.rs

A-replace:
- changed-files:
  - any-glob-to-any-file: backhand-cli/src/bin/replace.rs
