[package]
name = "squashfs-deku"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deku = { git = "https://github.com/sharksforarms/deku.git" }
flate2 = "1.0.24"
xz2 = "0.1.7"
clap = { version = "4.0.12", features = ["derive"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
thiserror = "1.0.37"
