[target.x86_64-unknown-linux-musl]
pre-build = [
    "apt update && apt install zlib1g-dev liblzma-dev",
    "git clone https://github.com/plougher/squashfs-tools.git -b squashfs-tools-4.6.1 && cd squashfs-tools/squashfs-tools && CONFIG=1 XZ_SUPPORT=1 GZIP_SUPPORT=1 make && make install",
]

[build.env]
passthrough = [
    "RUST_LOG",
]
