on: [pull_request]
name: CI Pull Request
jobs:
  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
        with:
          fetch-depth: 0
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - uses: wcampbell0x2a/criterion-compare-action@20e6511506d7c141bcb0e336db78928cc5504870
        with:
          branchName: ${{ github.base_ref }}
          before: "cargo build --bins --release --locked --workspace"
          token: ${{ secrets.GITHUB_TOKEN }}
