on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ master ]

env:
  BINS: "add-backhand unsquashfs-backhand replace-backhand"

name: binaries

jobs:
  # release binaries
  release-bins:
    runs-on: ${{ matrix.job.os }}
    env:
      RUSTFLAGS: "-C target-feature=+crt-static"
      BUILD_CMD: cargo
    strategy:
      fail-fast: false
      matrix:
        job:
          - { target: x86_64-unknown-linux-musl,  os: ubuntu-latest, use-cross: true }
          - { target: aarch64-unknown-linux-musl, os: ubuntu-latest, use-cross: true }
          - { target: arm-unknown-linux-musleabi, os: ubuntu-latest, use-cross: true }
          - { target: x86_64-apple-darwin,        os: macos-12                       }

    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - name: Populate cache
        uses: ./.github/workflows/cache

      - name: Overwrite build command env variable
        if: matrix.job.use-cross
        shell: bash
        run: |
          echo "BUILD_CMD=cross" >> $GITHUB_ENV
          RUSTFLAGS="-C target-feature=-crt-static" cargo install cross --git https://github.com/cross-rs/cross

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          target: ${{ matrix.job.target }}

      - run: $BUILD_CMD build -p backhand-cli --bin add-backhand --bin replace-backhand --features xz-static --locked --target ${{ matrix.job.target }} --profile=dist
      # default features, but replace gzip with gzip-zune-inflate
      - run: $BUILD_CMD build -p backhand-cli --bin unsquashfs-backhand --locked --target ${{ matrix.job.target }} --profile=dist --no-default-features --features zstd,xz-static,gzip-zune-inflate
      - name: archive
        run: |
          tar -czvf backhand-${{ matrix.job.target }}.tar.gz \
              -C target/${{ matrix.job.target }}/dist/ $BINS

      - uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: backhand-${{ matrix.job.target }}.tar.gz
          path: backhand-${{ matrix.job.target }}.tar.gz

      # check semvar before release!
      - name: Check semver
        env:
          # disable static build for this job
          RUSTFLAGS: ""
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: obi1kenobi/cargo-semver-checks-action@48f4ef7da6d907d69d18249e0ba79aa98c61b9db # v2.3
        with:
          package: backhand

      - name: Upload binary to release
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: svenstaro/upload-release-action@04733e069f2d7f7f0b4aebc4fbdbce8613b03ccd # v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: backhand-${{ matrix.job.target }}.tar.gz
          asset_name: backhand-${{ github.ref_name }}-${{ matrix.job.target }}.tar.gz
          tag: ${{ github.ref }}
          prerelease: true
          overwrite: true
