on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ master ]

env:
  BINS: "add unsquashfs replace"

name: binaries

jobs:
  # release binaries
  release-bins:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-C target-feature=+crt-static"
    strategy:
      matrix:
        targets:
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl
          - arm-unknown-linux-musleabi
          - mips-unknown-linux-musl
          - mipsel-unknown-linux-musl

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.targets }}
      - run: cargo install cargo-quickinstall
      - run: cargo quickinstall cross@0.2.5 --force
      - run: cross build --bins --locked --target ${{ matrix.targets }} --profile=dist

      - name: archive
        run: |
          tar -czvf backhand-${{ matrix.targets }}.tar.gz \
              -C target/${{ matrix.targets }}/dist/ $BINS

      - uses: actions/upload-artifact@v3
        with:
          name: backhand-${{ matrix.targets }}.tar.gz
          path: backhand-${{ matrix.targets }}.tar.gz

      # check semvar before release!
      - name: Check semver
        env:
          # disable static build for this job
          RUSTFLAGS: ""
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: obi1kenobi/cargo-semver-checks-action@v2

      - name: Upload binary to release
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: backhand-${{ matrix.targets }}.tar.gz
          asset_name: backhand-${{ github.ref_name }}-${{ matrix.targets }}.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
