name: Coverage

on: [pull_request, push]

permissions:
  contents: read

jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    strategy:
      matrix:
        toolchain:
          - stable

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Populate cache
        uses: ./.github/workflows/cache

      - run: sudo apt-get install -y squashfs-tools

      - uses: dtolnay/rust-toolchain@be73d7920c329f220ce78e0234b8f96b7ae60248 # master
        with:
          toolchain: ${{ matrix.toolchain }}

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@e8c64729e2a2a2c3cfa6751fa496b34ca19f390c # cargo-llvm-cov

      # generate release builds of the testable binaries
      # this is meant to actually run the binary, so this will fail but the binary will be built
      - run: cargo llvm-cov run --bin replace-backhand --no-clean --release || true
      - run: cargo llvm-cov run --bin add-backhand --no-clean --release || true
      - run: cargo llvm-cov run --bin unsquashfs-backhand --no-clean --release || true

      # run coverage on tests
      - run: cargo llvm-cov --workspace --codecov --output-path codecov.json --features __test_unsquashfs --release --no-clean -- --skip slow

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@0cfda1dd0a4ad9efc75517f399d859cd1ea4ced1 # v4.0.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: codecov.json
          fail_ci_if_error: true
